@scheme = https
@testeodh = workspaces.test.eodhp.eco-ke-staging.com
@ades = test.eodatahub.org.uk/ades
@username= sam-malone41
@workspace = workspace
@s3Endpoint = AccessPointName-AccountId.s3-accesspoint.region.amazonaws.com
@fileName = <WORKSPACE NAME>/<FILENAME>.tif
@logindetails = 454f44482c4c3dae5a4c52913e7a2dea
@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}


###
# example from GitHub guide
# @name accessFileInWorkspace
GET /files/<bucket_name>/<path_to_file> HTTP/1.1
Host: {{workspace}}.workspaces.test.eodhp.eco-ke-staging.com
Authorization: Bearer {{logindetails}}

###

# @name TestUserDatasetsAccess
GET /https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user-datasets/sam-malone41/processing-results
Authorization: Bearer 454f4448b51f097304fd2fc42b66a394
Accept: application/json

########



# @name deleteProcess
DELETE https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes/qa-workflow HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###

# @name listProcesses
GET https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###
#https://staging.eodatahub.org.uk/ades/npl/ogc-api/processes
#https://npl.staging.eodatahub-workspaces.org.uk/ogc-api/processes
#/api/catalogue/stac/catalogs/user/catalogs/sam-malone41/processes

# @name deployProcessJson
POST https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json
Content-Type: application/cwl+yaml

< qa-workflow.cwl


###
# need to update url
# @name getDeployStatus
GET deployProcessJson.response.headers.Location HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###
# @name executeProcess
POST https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes/qa-workflow/execution HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {"s3_endpoint": "AccessPointName-AccountId.s3-accesspoint.region.amazonaws.com",
   "qa_check_type": "radiometric_unc",
   "date_range": "2022-01-01,2022-12-31",
   "data_collection": "airbus_phr"
}
}


###
# need to update url with job id
# @name getExecuteStatus
GET https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/jobs/a66638d2-0af0-11f0-b2a8-de263ce83925 HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###
# need to update url to include correct job code a88a2af4-05ca-11f0-bbc3-eadd75232b79
# @name getProcessingResults
GET 8iu970fcf1314-05c6-11f0-b647-eadd75232b79/results HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


### /api/catalogue/stac/catalogs/user/catalogs/<workspace>/processes /api/catalogue/stac/catalogs/user/catalogs/<workspace>/jobs

# @name getProcessDetails
GET https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes/qa-workflow HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###

# @name listJobs
GET https://staging.eodatahub.org.uk//api/catalogue/stac/catalogs/user/catalogs/npl/jobs HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###

# @name listJobResults
GET https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sam-malone41/jobs/056c7570-0980-11f0-9416-fe2846126905/results HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###

# @name listCatalogsAndCollections
GET https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sam-malone41/catalogs/processing-results/catalogs/qa-workflow/search HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###

# @name listoutputsinmyworkspace
GET https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/jobs/a66638d2-0af0-11f0-b2a8-de263ce83925/results HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###


# @name getDocReviewResults
GET https://npl.staging.eodatahub-workspaces.org.uk/files/workspaces-eodhp-staging/processing-results/qa-workflow/sentinel-2_l1c_qa/qa_documentation/output_sentinel-2_l1c_qa_check_doc_review.json HTTP/1.1
Authorization: Bearer 454f4448c135f8695053f70d54fc5eb8
Accept: application/json


###
https://staging.eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sam-malone41/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/collections