###

# @name deleteProcess
DELETE https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes/qa-workflow HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###

# @name listProcesses
GET https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###

# @name deployProcessJson
POST https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json
Content-Type: application/cwl+yaml

< qa-workflow.cwl


###
# need to update url
# @name getDeployStatus
GET deployProcessJson.response.headers.Location HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###
# @name executeProcess
POST https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes/qa-workflow/execution HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {"s3_endpoint": "AccessPointName-AccountId.s3-accesspoint.region.amazonaws.com",
   "qa_check_type": "radiometric_unc",
   "date_range": "2022-01-01,2022-12-31",
   "data_collection": "s2a"
}
}
### "2025-03-25",

###
# need to update url with job id
# @name getExecuteStatus
GET https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/jobs/63eba338-484a-11f0-9935-8235d858a0f5 HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###
# need to update url to include correct job code a88a2af4-05ca-11f0-bbc3-eadd75232b79
# @name getProcessingResults
GET 8iu970fcf1314-05c6-11f0-b647-eadd75232b79/results HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


### /api/catalogue/stac/catalogs/user/catalogs/<workspace>/processes /api/catalogue/stac/catalogs/user/catalogs/<workspace>/jobs

# @name getProcessDetails
GET https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/processes/qa-workflow HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###

# @name listJobs
GET https://eodatahub.org.uk//api/catalogue/stac/catalogs/user/catalogs/npl/jobs HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###

# @name listJobResults
GET https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/jobs/4aab56c4-2749-11f0-94ae-1a1f07364587/results HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###

# @name listCatalogsAndCollections
GET https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/catalogs/processing-results/catalogs/qa-workflow/search HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###

# @name listoutputsinmyworkspace
GET https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/npl/jobs/a66638d2-0af0-11f0-b2a8-de263ce83925/results HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###


# @name getDocReviewResults
GET https://npl.eodatahub-workspaces.org.uk/files/workspaces-eodhp/processing-results/qa-workflow/sentinel-2_l1c_qa/qa_documentation/output_sentinel-2_l1c_qa_check_doc_review.json HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###


# @name getRadUncResults
GET https://npl.eodatahub-workspaces.org.uk/files/workspaces-eodhp/processing-results/qa-workflow/sentinel-2_l1c_qa/qa_radiometric/output_sentinel-2_l1c_qa_check_radiometric_unc_2022-02-01_2022-02-28.json HTTP/1.1
Authorization: Bearer TOKEN
Accept: application/json


###
https://eodatahub.org.uk/api/catalogue/stac/catalogs/user/catalogs/sam-malone41/catalogs/processing-results/catalogs/qa-workflow/catalogs/airbus_phr_qa/collections
sentinel-2_l1c_qa/qa_documentation/output_sentinel-2_l1c_qa_check_doc_review.json
airbus_phr_qa/qa_documentation/output_airbus_phr_qa_check_doc_review.json
planet_psscene_qa/qa_radiometric/output_planet_psscene_qa_check_radiometric_unc_2022-02-01_2022-02-28.json
